name: Tag
on:
  workflow_dispatch:
    inputs:
      toBeTagAsLatestV4:
        description: 'The image tag which will be tag as latest-v4'
        required: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Pull and push image
        run: |
          docker pull ${{ secrets.DOCKERHUB_USERNAME }}/tinymediamanager:${{ github.event.inputs.toBeTagAsLatestV4 }}
          docker tag ${{ secrets.DOCKERHUB_USERNAME }}/tinymediamanager:${{ github.event.inputs.toBeTagAsLatestV4 }} ${{ secrets.DOCKERHUB_USERNAME }}/tinymediamanager:latest-v4
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/tinymediamanager:latest-v4
